# Generated by Django 5.0.2 on 2024-03-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Название')),
                ('students', models.TextField(blank=True, null=True, verbose_name='Ученики')),
                ('link', models.CharField(max_length=25, verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Название')),
                ('src', models.TextField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('link', models.CharField(max_length=25, verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=25, verbose_name='Автор')),
                ('title', models.CharField(max_length=25, verbose_name='Название')),
                ('min_group', models.IntegerField(verbose_name='Минимальный размер группы')),
                ('max_group', models.IntegerField(verbose_name='Максимальный размер группы')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
